services:
  saleor-storefront:
    container_name: saleor-storefront
    build:
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SALEOR_API_URL: https://api.saleor.tattoogoat.com/graphql/
        NEXT_PUBLIC_STOREFRONT_URL: https://storefront.saleor.tattoogoat.com
        NEXT_PUBLIC_CHECKOUT_URL: https://storefront.saleor.tattoogoat.com/checkout/
    environment:
      - NEXT_PUBLIC_SALEOR_API_URL=https://api.saleor.tattoogoat.com/graphql/
      - NEXT_PUBLIC_STOREFRONT_URL=https://storefront.saleor.tattoogoat.com
      - NEXT_PUBLIC_CHECKOUT_URL=https://storefront.saleor.tattoogoat.com/checkout/
    restart: always
    ports:
      - 3030:3030
    networks:
      - saleor_network

  # Add more containers below (nginx, postgres, etc.)

networks:
  saleor_network:
    external: true
    name: saleorgoat_network
